apiVersion: v1
kind: Service
metadata:
  name: dev-nginx-service
  namespace: dev
spec:
  selector:
    app: dev-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP