apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-nginx
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staging-nginx
  template:
    metadata:
      labels:
        app: staging-nginx
    spec:
      containers:
        - name: nginx
          image: 495278513365.dkr.ecr.ap-south-1.amazonaws.com/cicd-rollback-pipeline:staging-latest
          ports:
            - containerPort: 80