apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-nginx
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staging-nginx
  template:
    metadata:
      labels:
        app: staging-nginx
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: nginx
          image: 495278513365.dkr.ecr.ap-south-1.amazonaws.com/cicd-rollback-pipeline@sha256:7169261a9f2a86ce293e07d3bf0945c7e62e0c6e3b51be3c8f8b3425434a86a0
          ports:
            - containerPort: 80